version: '3.8'
services:
  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddog_dog_test
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    networks:
      - monitoring

  spring-boot-app:
    image: ddogdog:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ddog_dog_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JAVA_OPTS: "-Xms1g -Xmx1g"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge